baseURL = ""
languageCode = "en-uk"
title = "Sam Carter Blog"
theme="sam"
googleAnalytics = "UA-120276662-1"

[[params.mainMenu]]
    link = "/posts"
    text = "writing"

[[params.mainMenu]]
    link = "/eyes"
    text = "eyes"

[[params.mainMenu]]
    link = "/yoga"
    text = "yoga"

[[params.mainMenu]]
    link = "/about"
    text = "about"

